server:
  port: 8081

spring:
  application:
    name: spring-boot-library
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./h2/spring-boot-library-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE;
    name: spring-boot-library
    username: spring-boot-library
    password: spring-boot-library
  jackson:
    default-property-inclusion: NON_NULL
    deserialization:
      adjust-dates-to-context-time-zone: false
      fail-on-unknown-properties: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true