logging:
  config: classpath:logback-spring.xml
  level:
    ROOT: INFO

server:
  port: 8080

spring:
  application:
    name: spring-boot-library
  data:
    rest:
      default-page-size: 20
      max-page-size: 1000
  datasource:
    platform: postgresql
    url: jdbc:postgresql://${POSTGRES_SERVER:localhost:5432}/spring-boot-library
    initialization-mode: always
    name: spring-boot-library
    username: spring-boot-library
    password: spring-boot-library
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false
      fail-on-unknown-properties: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        generate_statistics: false
        jdbc:
          batch_size: 1000
          lob:
            non_contextual_creation: true
        order_inserts: true
    show-sql: true